version: '3.8'

services:
  f1ops:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: f1ops-dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data:ro
      - ./artifacts:/app/artifacts
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
    restart: unless-stopped
